### ISSUE TITLE
Multiline macros sometimes (often?) come out in wrong order

### ISSUE THREAD

**Issue by rbrian** [mike1pol/octoprint_macro#10]
For example, I have a macro like this: 

g28
g0 x0 y0 z5 f3000
g0 z.1 f1500

a good portion of the time, it works as expected. Sometimes, however, it will execute as 

g28
g0 z.1 f1500
g0 x0 y0 z5 f3000

which of course isn't terribly useful. :) 

Using Octoprint 1.4.2, Klipper firmware. I'll be glad to help diagnose this any way I can.

**Comment by mike1pol** [comment]
i'll try to check it

**Comment by Matejz90** [comment]
I have too this issue. Like:
M851 Z-2.60
M500
M501

Come out 
M851 Z-2.60
M501
M500

Thanks!

//Edit: @mike1pol if you add one second pause between each loop irritation in macro.js then code work flawless because loop is too fast for execute

[macro.zip](https://github.com/mike1pol/octoprint_macro/files/5373761/macro.zip)
